### ISSUE TITLE
Improve/fix gitlab connection form to support multi repositories projects

### ISSUE THREAD

**Issue by Marthym** [nhat-phan/merge-request-integration#1]
Is it usable for projects with modules form multiple git repository ?

I see only merge requests form "Local Project"

**Comment by nhat-phan** [comment]
@Marthym yes, you can setup multiple connection, 1 connection will point to 1 git repository in your project

**Comment by Marthym** [comment]
Ok, I have try multiple connection (I have something like 15 projects :s) but the plugin does not works with multiple connection, I'm not able to change Local Repository or delete connection.

**Comment by nhat-phan** [comment]
I refactored the configuration page, tested with 3 repositories on a project, hope it works for you now.

**Comment by Marthym** [comment]
Yes it seems to be good now

Thanks
