### ISSUE TITLE
Add "jump to code" option for comments

### ISSUE THREAD

**Issue by peper0** [nhat-phan/merge-request-integration#14]
It is related to  #3 but, I believe, much easier to implement.

**Comment by smec-cgint** [comment]
Hi @nhat-phan 

I would really be happy about this feature. Currently the only thing I am missing.
The other functionalities are already awesome and very useful.

Thanks
Christian

**Comment by nhat-phan** [comment]
I've merged a big feature #3 , right now you can see, write and reply comments in the diff view. Unfortunately the comments tree is not compatible so I can open the diff view only (can't jump to the line where has comments).

The problem will be solved when I refactor the comments tree completely.
