### ISSUE TITLE
Pipeline status

### ISSUE THREAD

**Issue by vdsirotkin** [nhat-phan/merge-request-integration#16]
Hi. I have a repository in private GitLab installation, which has "only merge_requests" pipeline. But i haven't got pipeline status visible in extension interface. What information do you need from me to help you with investigation about this issue? Thank you

**Comment by nhat-phan** [comment]
Hi vdsirotkin,

Can you see the pipeline in the merge request toolbar which looks like this:

<img width="479" alt="Screen Shot 2020-01-24 at 15 54 47" src="https://user-images.githubusercontent.com/34987391/73056612-17143800-3ec2-11ea-891d-2c11b6d69a0a.png">

If you can't see it, please provide these information:

- Your OS: Windows, macOS or Linux
- The IDE version
- The self-hosted GitLab version + package: Free, Bronze, Silver or Gold

Thank you for reporting.

**Comment by vdsirotkin** [comment]
Yeah, i've seen such screenshot earlier, but i don't have such information there. 
* OS: MacOS
* IDEA 2019.3.2
* GitLab Community Edition 12.2.4 and free plan

**Comment by nhat-phan** [comment]
Fixed by @turnik. Will be available since v2019.3.4 (expected release this weekend - Feb 2nd 2020)
