### ISSUE TITLE
SSLHandshakeException when trying to add a server

### ISSUE THREAD

**Issue by edoreld** [nhat-phan/merge-request-integration#19]
I am unable to reopen the previous related issue, so that's why I am opening this one.

Error when trying to add a server:
<img width="441" alt="Screenshot 2020-01-28 at 11 20 12" src="https://user-images.githubusercontent.com/973854/73255275-2cd67580-41c0-11ea-9425-591b8483e136.png">

Context:
Tools -> Server Certificates |> "Accept non-trusted certificates automatically" [ON]
Tools -> Server Certificates |> Certificate of server added
Server certificate added to cacerts for all of my jdks as per the related issue https://github.com/nhat-phan/merge-request-integration/issues/2

**Comment by nhat-phan** [comment]
The SSL error is on master but I can't release it yet. It will be available since v2019.3.4. I keep this one open and close when the new version is released.
