### ISSUE TITLE
SSLHandshakeException with local gitlab and self-created certificate

### ISSUE THREAD

**Issue by theotherp** [nhat-phan/merge-request-integration#2]
I'm getting this error: `Cannot connect, error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` when trying to connect to the self-hosted local Gitlab with a self-created certificate.

I allowed IntelliJ to "Accept non-trusted certificates automatically", added the certificate to IntelliJ and even the JBR cacerts file. 

How do you do the connections to gitlab? What would I need to do to get this fixed? 

Thanks, the plugin looks exactly like what I'd need.

**Comment by theotherp** [comment]
Nvm, I forgot to actually save the cacerts file... 

Perhaps this will help others with this problem.

**Comment by nhat-phan** [comment]
@theotherp Could you please tell me how you solved the problem? 

Some developers also use self-signed certificate and request _an ignore SSL exception option_ which I'm working on. Your idea will be of great help when I am still working on the feature.

**Comment by theotherp** [comment]
I added the certificate to the the JBR cacerts file (can easily be done
using cert explorer).

Isn't there a way for you to use the intellij API to communicate with
gitlab? Intellij has a dialog for certificates and an option to
automatically accept unkon ones.
