### ISSUE TITLE
Connection configuration page only shows the 1st 10 projects

### ISSUE THREAD

**Issue by riclucio** [nhat-phan/merge-request-integration#22]
When I'm creating a new connection, when I try to search for a project, it only brings me the 1st 10 matches, without scroll options, thus if my option is after the 1st 10 chunk, I cannot select it.
![image](https://user-images.githubusercontent.com/48838923/73841391-4b102700-47f9-11ea-84de-426829460163.png)
In my case above, my project name is simply "Vault", there is no way to be more precise, but as other projects also have the word "vault", I cannot see my option for pick.

**Comment by nhat-phan** [comment]
@riclucio could you please use Starred/Membership/Own options to shorten the list?

**Comment by riclucio** [comment]
@nhat-phan that helped, just had to go to gitlab web and star the Vault project.
Thanks! This unblocked me.
But I still think this should be improved to allow scrolling on the options.
Should this be changed to an enhancement request?

**Comment by kortov** [comment]
As I understand JList of projects should be embed it in a JScrollPane? I've not code in swing, just tried to investigate it of curiousity

**Comment by nhat-phan** [comment]
Currently there is no JScrollPane which wraps the JList. I remember the reasons I don't use JScrollPane are:

- To keep the project as clear as possible. If scroll view is introduced maybe the selected project will not be in the viewable area.
- Sub-filters (Starred/Membership/Own) can be used to shorten the list.

To solve this problem completely, I'm trying to use remote information of repository to get the project selected automatically or support search projects by id/url.
