### ISSUE TITLE
Plugin settings not retained

### ISSUE THREAD

**Issue by ggavigli** [nhat-phan/merge-request-integration#28]
I uninstalled my previous gitlab plugins and installed the eval version of merge request plugin.

I then went into Other Settings > Merge Request Integration > GitLab plugin configuration and modified the settings for my organization.  

I then "Test Connection" and the settings pass.  

I then click OK but when I go back into the settings panel all my changes are gone...

Before OK:
![image](https://user-images.githubusercontent.com/12973962/74213408-e831ec00-4c4d-11ea-82a8-f781101c7b4d.png)

After OK:
![image](https://user-images.githubusercontent.com/12973962/74212925-a0aa6080-4c4b-11ea-839e-2f4d4a007fe3.png)

Note that the "Apply" button is never enabled no matter how many changes I make to the merge request plugin configuration.

**Comment by ggavigli** [comment]
Forgot to specify that I'm using IntelliJ IDEA Ultimate V2019.3.2 and V2019.3.5 Trial version of the plugin.

**Comment by nhat-phan** [comment]
Thank for reporting the problem.

I've tried to reproduce it but it seems flaky, I don't know exactly the root cause. 

It works for me with the option "Share credentials with other projects" on, maybe it unblocks you for now.

**Comment by nhat-phan** [comment]
@ggavigli did you choose the project? 

You can use "Search project..." textfield to find the project, then select it. The screenshot looks like this:

<img width="724" alt="project-selected" src="https://user-images.githubusercontent.com/34987391/74222471-e2232600-4cb4-11ea-8d53-807c35f11b82.png">

If everything's okay, the apply button will be enabled.

**Comment by ggavigli** [comment]
I can't tell if this is an issue where my Project search text brings back too many results and therefore takes so long that I never see an actual repo listed or if there is a UI bug.  What I found works for me is to narrow down the search text enough such that only the repo I want is found.  Entering the text is not enough, I have to select one of the "starred"/"membership"/"own" check boxes otherwise the search doesn't happen.  

In regards to this particular issue I have figured out how to do what I want now so I will close this bug but I would suggest adding a spinner when the search is happening so that users know they may be on the right path to figuring out why things might not work as expected.

**Comment by ggavigli** [comment]
Would you suggest creating a separate merge request configuration tab for each project?  For example I have the following repos and I load them in separate InelliJ projects:
datg-eia/repo1
datg-eia/repo2

Should I create two different merge request configs (repo1 and repo2) and in the repo1 project select the repo1 merge request configuration tab and in the repo2 project select the repo2 merge request configuration tab?

Gregg

**Comment by nhat-phan** [comment]
It's up to you.

Personally, I prefer setup connection based on number of repositories in your project. For example: I have 2 Intellij project windows:

- The first one it's a monolith -> I setup only 1 connection
- The second one there are 2 repositories -> I setup 2 connections

I have a plan to introduce notification feature that you're notified whenever you have new MR to review, I'll take this scenario into consideration when implementing the feature.

Please let me know if you have any other question.

**Comment by nhat-phan** [comment]
linked issue: https://github.com/nhat-phan/merge-request-integration/issues/22
