### ISSUE TITLE
Feature Request: Allow code review without checking out the branch

### ISSUE THREAD

**Issue by riclucio** [nhat-phan/merge-request-integration#33]
Currently, when we click on "Code Review" button, it checks out the branch being reviewed.
This maybe an issue when I want to do multi-tasking and stop a WIP changes on my local and do some code reviews, if these changes conflict with the changes in the branch I'm about to review.
This demands me either commit (which I may not be ready for) or stash my changes before I click "Code Review" on a merge request.

It would be good if I could perform the code review without having to switch branches if possible.

**Comment by riclucio** [comment]
My main point here is: I should not have to alter my local environment just to perform a code review.

**Comment by nhat-phan** [comment]
The main reason to checkout the branch is you can navigate through the code with side-by-side view. I think some people love that therefore I'll introduce this feature as an option in configuration.

Thank you for your ideas and requests 😄

**Comment by riclucio** [comment]
But don't you need just the diff of the files in the branch in review to generate the side-by-side view?
You can get the diff with `git diff master...my_branch_to_merge`.
Anyway, a config option to do code review without branch checkout should be fine.

**Comment by nhat-phan** [comment]
In the very next version (v2020.1.0) the plugin will support an option which do not checkout to target branch when doing code review.

Please note that the option is enabled by default, so you have to uncheck it manually in configuration:

<img width="743" alt="Screen Shot 2020-02-22 at 20 56 55" src="https://user-images.githubusercontent.com/34987391/75098416-316f2d80-55b6-11ea-88a3-345938122529.png">

**Comment by riclucio** [comment]
Great! Thanks for taking care of it!

**Comment by theotherp** [comment]
Sounds great. What would be a reason not to enable this? Does it provide less features?
