### ISSUE TITLE
Feature Request: Allow adding general comments

### ISSUE THREAD

**Issue by riclucio** [nhat-phan/merge-request-integration#35]
Currently there is no way to add general comments to the merge request.
To do so I need to go to the web interface and add it from there.

It would be good to allow adding general comments right from the IDE.

**Comment by nhat-phan** [comment]
There is an option to add a general comment if the checkbox "Add comment to the..." is unchecked.

<img width="692" alt="Screen Shot 2020-02-13 at 20 02 04" src="https://user-images.githubusercontent.com/34987391/74468837-ce85e400-4e9b-11ea-9806-b8701a56a19a.png">

I think maybe introduce new context menu to add a general comment is clearer way, right?

**Comment by riclucio** [comment]
I think I'm missing a  button to add a general comment right above the list of comments, as below in red:
![image](https://user-images.githubusercontent.com/48838923/74489973-ccc11e00-4ea5-11ea-86e7-814175d54b6b.png)
Or close to the buttons in the right toolbar:
![image](https://user-images.githubusercontent.com/48838923/74490043-0eea5f80-4ea6-11ea-8038-30e5dc782486.png)
What do you think?

**Comment by nhat-phan** [comment]
I think that area suppose to contains another tabs or another actions, maybe an action "Add General Comment" makes more sense if it's in this area:

![Screen Shot 2020-02-14 at 21 40 03](https://user-images.githubusercontent.com/34987391/74566010-ca78c580-4f72-11ea-9a18-a53c49250d1d.png)

**Comment by riclucio** [comment]
Yeah that should work.

**Comment by nhat-phan** [comment]
The feature will be available in next version, looks like this

<img width="487" alt="Screen Shot 2020-02-19 at 20 53 47" src="https://user-images.githubusercontent.com/34987391/74870642-5cf5dc00-535a-11ea-9a0b-b5729ae8da40.png">

**Comment by riclucio** [comment]
Nice! Thanks for taking care of it!
