### ISSUE TITLE
Clicking "add comment" in editor does not open the comment field

### ISSUE THREAD

**Issue by Tillerino** [nhat-phan/merge-request-integration#37]
When the "Merge Request Integration CE" panel is showing and I click "add comment" in the editor, the cursor automatically jumps into the commend field - perfect.

However, when I click "add comment" in the editor while the "Merge Request Integration CE" panel is _hidden_, the comment field remains hidden because the "Merge Request Integration CE" panel does not automatically show. Initially, I thought the feature was broken :)

**Comment by nhat-phan** [comment]
Thank you for letting me know. 

In the next version, the comment detail will be displayed right after replying/creating a general or diff comment.
