### ISSUE TITLE
EE version doesn't show GitLab server/merge requests

### ISSUE THREAD

**Issue by rusch36** [nhat-phan/merge-request-integration#38]
After purchasing of Merge Request Integration EE and activating it, clicking on refresh button on "Home" tab doesn't show configured GitLab server. CE version of plugin is functional, server & merge requests visible.

There is same configuration for CE && EE version. CE is not installed together with EE version.

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to Home Credit International a.s.

Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: 
Non-Bundled Plugins: Jetbrains TeamCity Plugin, Jira Browser, com.intellij.kubernetes, net.ntworld.nhat-phan.merge-request-integration-ee

**Comment by nhat-phan** [comment]
Thank you for purchasing and reporting.

Technically the plugins share the same code. I'll double check and fix it if it's reproducible.

**Comment by rusch36** [comment]
Thank you. If there is an information which could help, please let me know.

**Comment by rusch36** [comment]
Can be closed now! It's already working in the last EAP Idea version. Thanks!  👍

**Comment by nhat-phan** [comment]
Thank you for letting me know 👍
