### ISSUE TITLE
This plugins is incompatible with latest Android Studio 3.6.3 (stable)

### ISSUE THREAD

**Issue by mochadwi** [nhat-phan/merge-request-integration#55]
We (our teams) really appreciate and what're you doing so far building this plugins/tools integration to reduce our multitask, and keep productive inside Android Studio. 

Unfortunately, we're still using Android Studio 3.6.3 stable, (and maybe won't update it until AS/AGP 4.x became stable), therefore we cannot use your plugins, because it won't works for below `Intellij IDEA 193.x builds`

Here's our IDEs version:
```
Android Studio 3.6.3
Build #AI-192.7142.36.36.6392135, built on April 14, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.new.welcome.screen.force=true, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false
Non-Bundled Plugins: commit-template-idea-plugin, org.jetbrains.kotlin, com.google.services.firebase, io.github.lizhangqu.intellij.plugin.android.bundle, wu.seal.tool.jsontokotlin
```

Screenshot:
1. <img width="358" alt="Screen Shot 2020-04-21 at 5 39 31 PM" src="https://user-images.githubusercontent.com/7057959/79856989-4d951c80-83f7-11ea-8103-a3630a82d539.png">
2. <img width="634" alt="Screen Shot 2020-04-21 at 5 38 35 PM" src="https://user-images.githubusercontent.com/7057959/79856994-4f5ee000-83f7-11ea-819d-8d3a2108e666.png">
3. <img width="429" alt="Screen Shot 2020-04-21 at 5 39 44 PM" src="https://user-images.githubusercontent.com/7057959/79856977-4a019580-83f7-11ea-9afe-717e6c8ff16d.png">

Thanks in advances for this great tools :) Do you have any plan to integrate this plugins for 192.x intellij idea builds?

**Comment by nhat-phan** [comment]
Sorry, this plugin only available for IDE based on above IntelliJ IDEA 193.* , it means only available since Android Studio 4.0.0
