### ISSUE TITLE
Licensing Problem

### ISSUE THREAD

**Issue by miharp** [nhat-phan/merge-request-integration#64]
I bought EE license but it still shows Illegal? How can I get the license applied correctly?

**Comment by nhat-phan** [comment]
Thank you for using EE edition.

I forwarded to Jetbrains already. To solve it maybe they will ask you some information.

I'll keep you updated. Cheer!

**Comment by LChernigovskaya** [comment]
Hi @miharp,

Could you please check that you activated your license? To do this please go to Help | Register...

**Comment by miharp** [comment]
Ah, Help->Register was the piece missing. Working now, Thanks

**Comment by nhat-phan** [comment]
@LChernigovskaya thank you for your fantastic support.

@miharp thanks again for your purchase, it helps me improve the plugin continuously, I hope you love the plugin. Cheers!
