### ISSUE TITLE
Loading data and refreshing not working properly

### ISSUE THREAD

**Issue by srinathanantha** [nhat-phan/merge-request-integration#65]
There are issues with with loading data. As you can see from images its not loading data. And even when there are merge requests assigned to me, its not showing in the list. It showed the list the first time and after I closed the "Default" tab for that provider, it stopped working.

![image](https://user-images.githubusercontent.com/1021690/80919843-26651600-8d3a-11ea-8f66-1d8c6425c73f.png)

![image](https://user-images.githubusercontent.com/1021690/80919885-57dde180-8d3a-11ea-98a2-f858eb3c73f5.png)

**Comment by nhat-phan** [comment]
Thank you for reporting the problem. It's fixed already will be available in very next version. 

In the meantime, you can click Refresh button (in the top left, picture 2) to reload the provider list, it will be okay
