### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by jlhitt** [nhat-phan/merge-request-integration#74]
I am using IntellIJ IDEA Ultimate, and recently converted from my personal license for IntelliJ to a company license, and this is what is used via "Help -> Register".

I purchased a year long license for Merge Requests Integration EE, via my personal account.

It appears that plugin licenses are "bundled" with main licenses?  Is that true? 

There does not appear to be a way to do "multiple license keys" within the Jetbrains products. 

Suggestions?

**Comment by LChernigovskaya** [comment]
Hello @jlhitt,
You can use personal license for the plugin while having company license for IntelliJ IDEA Ultimate. These licenses are not related. Please check that the plugin is enabled (in Plugin Manager) and then go to 'Help -> Register...' as well and activate your personal license for plugin there.

**Comment by jlhitt** [comment]
@LChernigovskaya Thank you for the input.  After restarting IntelliJ, it prompted me for the license activation key and everything appears to be working as expected.
