### ISSUE TITLE
Incompatible with IJ 2020.2

### ISSUE THREAD

**Issue by lohengrin332** [nhat-phan/merge-request-integration#86]
My system recently updated IntelliJ to v 2020.2, and Merge Request Integration EE is marked as "Incompatible (until build 201.SNAPSHOT < IO-202.6397.94). Below is my current version and installed plugins. Please let me know if you need any further information in order to address this issue. Thank you.

IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-42-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: search.everywhere.settings=true
Non-Bundled Plugins: IdeaVIM, com.google.bamboo.id, CheckStyle-IDEA, com.intellij.plugins.watcher, io.protostuff.protostuff-jetbrains-plugin, org.apache.pig.plugin.idea, org.jetbrains.plugins.localization, org.jetbrains.plugins.rest, intellij.prettierJS, Pythonid
Current Desktop: i3

**Comment by jmatthiesen81** [comment]
Same here. I bought the Merge Request Integration **EE** Version, when will the compatibility update be ready?

**Comment by nhat-phan** [comment]
Sorry for late reply, I've been busy lately. New version compatible with 2020.2 will be available next week.
