### ISSUE TITLE
Incompatible with 2020.2

### ISSUE THREAD

**Issue by johnhenaot** [nhat-phan/merge-request-integration#87]
updated IntelliJ to v 2020.2, and Merge Request Integration **CE** is marked as Incompatible

**Comment by pchelk1n** [comment]
same for phpstorm

**Comment by tlttnz2018** [comment]
Vote this up. Happen for quite a long time :(.

**Comment by nhat-phan** [comment]
Sorry for late reply, I've been busy lately. New version compatible with 2020.2 will be available next week.
