### ISSUE TITLE
Search by MR id

### ISSUE THREAD

**Issue by bironran** [nhat-phan/merge-request-integration#89]
Often my coworkers (who don't use the plugin - shame!) will paste a gitlab URL that contains the MR id but not the issue id. I have to open gitlab in my browser just to copy the issue id and search it in the IDE. If I could search by the MR id directly, that would save me one extra step per MR.

**Comment by Borginator** [comment]
So this might also be way outside the scope of the project too, but my team has LOADS of projects. I'd love it if the link could open the correct project in IntelliJ too. I appreciate that It's an even bigger problem than @bironran was requesting for, but it's related in that we're talking about supporting a merge request link from gitlab. I doubt it's possible, but if someone has ideas, that'd be amazing.

**Comment by nhat-phan** [comment]
If you have a lot of projects, I think a chrome extension which supports open an MR directly is a best way.

Gitlab api has option to search by ID, so it's doable. I'm thinking that maybe introduce quick search by id option whenever you input an integer in this text box:

![Screen Shot 2021-01-04 at 21 12 05](https://user-images.githubusercontent.com/34987391/103575194-a0552c80-4ed1-11eb-993e-564343c6cfc2.png)

What do you think?

**Comment by bironran** [comment]
searching by merge request id would be a terrific solution for me. When pasted links look like this:

> https://my-company.com/group/project/-/merge_requests/12345

so I could just type 12345 and find the MR
