### ISSUE TITLE
Connection list isn't saving

### ISSUE THREAD

**Issue by mmjurov** [nhat-phan/merge-request-integration#9]
Added second connection to the settings:

![image](https://user-images.githubusercontent.com/802208/72686897-08b4cd80-3b0a-11ea-9bbf-efb745b2878c.png)

Click 'Delete this connection' - tab renames into (deleted):

![image](https://user-images.githubusercontent.com/802208/72686904-1a967080-3b0a-11ea-83ad-e4993c1e76db.png)

Then clicking ok in phpstorm settings window. When opening this settings page again I can notice that this connection wasn't deleted, it appears again like in the first screenshot.

The same behaviour when trying to add new connection to the another server.

Probably this issue appears after migrating from free plugin version to EE trial without PhpStorm restart. 

Reinstallation doesn't helps. 

Also a have noticed that when you change some setting in connections tab, phpstorm windows doesn't activate "Apply" button. Maybe it cannot detect that options cnahged?

![image](https://user-images.githubusercontent.com/802208/72687057-83321d00-3b0b-11ea-8335-d0cb1fae4c7e.png)

**Comment by nhat-phan** [comment]
Thank you for your feedback!

Could you please try to click "Refresh" button after setting up or deleting the second connection. Does it work for you?

<img width="265" alt="Screen Shot 2020-01-20 at 01 15 39" src="https://user-images.githubusercontent.com/34987391/72689732-d066bc80-3b14-11ea-833f-50b55147e329.png">

**Comment by mmjurov** [comment]
Unfortunally, it has no effect. I still cannot add new connection or delete the old ones.

**Comment by nhat-phan** [comment]
Thanks for your information. This definitely critical bug, should be fixed and released in next version.

In the meantime, you can remove connection by modifying the config file located in `.idea/merge-request-integration-ee.xml` or `.idea/merge-request-integration.xml`.
