### ISSUE TITLE
Hanging background tasks "fetching"

### ISSUE THREAD

**Issue by reitzig** [nhat-phan/merge-request-integration#95]
Throughout the day, new background tasks keep popping up that then hang and can not be cancelled:

![image](https://user-images.githubusercontent.com/4246780/91861992-b6c25180-ec6d-11ea-9178-85f29c7078b2.png)

The plugin seems to work normally.

This is on IDEA 2020.2.1.

**Comment by dragetd** [comment]
I can confirm the same behavior.

Private GitLab instance (with custom CA, ignoring certs), also hanging on that task. Happy to held debugging, if someone helps me on how to find out why it is hanging there. xD

**Comment by regevbr** [comment]
I can confirm the same behavior.

Private GitLab.com with private repos, also hanging on that task

**Comment by regevbr** [comment]
It seems like that it can't be cancelled on purpose:
https://github.com/nhat-phan/merge-request-integration/blob/a4c849c165615089527282946b1db155b17b461c/merge-request-integration-core/src/main/kotlin/net/ntworld/mergeRequestIntegrationIde/task/RegisterProviderTask.kt#L19

@nhat-phan why did you make the task not cancellable?

**Comment by vjuge** [comment]
I confirm I have the same issue on private repo (not tested on public repo)

**Comment by blejdfist** [comment]
Confirmed here also on a private repo

**Comment by HanSolo80** [comment]
I can confirm this issue on private repo as well.

**Comment by reitzig** [comment]
Can confirm that the "cancel" icon is now there -- but it doesn't cancel. The hanging tasks still mount up; 15 copies for me right now.

![image](https://user-images.githubusercontent.com/4246780/105521994-f94bff80-5cdc-11eb-80cc-9b236df1c89f.png)
