### ISSUE TITLE
EE version doesn't work with private repos

### ISSUE THREAD

**Issue by edvardpotter** [nhat-phan/merge-request-integration#96]
I bought EE license. But I still see an error that I have to buy it. How can I fix this?

![image](https://user-images.githubusercontent.com/16565815/92378244-90416200-f116-11ea-93da-b8eafd6af197.png)

![image](https://user-images.githubusercontent.com/16565815/92378337-b5ce6b80-f116-11ea-9561-0b54b5de746f.png)

**Comment by dragetd** [comment]
Did you install the non-CE version? Make sure you have the non-CE version installed (and the CE version uninstalled), then reboot IDEA. I also recently got a license and it works for me.

**Comment by edvardpotter** [comment]
It was Jet Brains plugin activation issue

**Comment by bironran** [comment]
@edvardpotter I have the same issue. how did you solve it?

**Comment by edvardpotter** [comment]
> @edvardpotter I have the same issue. how did you solve it?

You must remove CE-version, install  EE-version and after that paste your code in Licenses Window:
![image](https://user-images.githubusercontent.com/16565815/131630380-a37836db-60b5-4aa0-a88a-bc540b0a3bba.png)

P.S. Material Theme Plugin just for example.
